### ISSUE TITLE
Facit fonts in repository

### ISSUE THREAD

**Issue by justanotherfoundry** [rushir/rushir.github.io#1]
Dear Rushir Parikh,

We noticed that you are using our copyrighted JAF Facit fonts and redistributing them through this repository. 
We recommend that you remove the files (and purge them from your repository’s history) to avoid further action.

Sincerely,
Tim Ahrens
Just Another Foundry

**Comment by rushir** [comment]
Hey Tim,

I'm really sorry about that. I think what you are referring to is a typekit
reference in a file called *uzh1wki.js. *I just removed it.

I initially thought from reading your issue that the actual font file
(.woff or something similar) was found in my repository, however I myself
was unable to find it.

I'm very sorry, I had no intention on using or redistributing your JAF
Facit font, I was merely using that file (_uzh1wki.js)_ as a template and
hadn't gotten to editing it yet.

If you have found the font somewhere else in the repository, please let me
know, and I will remove it immediately.

Best,
Rushir
